"""
engine/legality.py

The "Architect" that enforces the laws of chess physics.
Every move generated by the LLM must pass through this validator.
Keeps the dream honest.
"""

import re
import io
from typing import Tuple, List, Optional
import chess
import chess.pgn
from dataclasses import dataclass


@dataclass
class LegalityReport:
    """Result of a legality check."""
    is_legal: bool
    error_message: Optional[str] = None
    move_object: Optional[chess.Move] = None
    position_fen: Optional[str] = None


class LegalityValidator:
    """
    Validates chess moves and games against the laws of chess.
    Uses python-chess as the ground truth.
    """

    # Pattern to match algebraic notation
    MOVE_PATTERN = re.compile(
        r"^([KQRBN])?([a-h])?([1-8])?x?[a-h][1-8](?:=[QRBN])?[+#]?$"
    )
    CASTLING_PATTERN = re.compile(r"^O-O(?:-O)?[+#]?$")

    def __init__(self):
        self.board = chess.Board()

    def reset_board(self, fen: Optional[str] = None) -> None:
        """Reset the board to starting position or a specific FEN."""
        if fen:
            self.board = chess.Board(fen)
        else:
            self.board = chess.Board()

    def validate_move_notation(self, move_str: str) -> bool:
        """Check if the move string matches valid algebraic notation."""
        move_str = move_str.strip()
        return bool(self.MOVE_PATTERN.match(move_str)) or bool(
            self.CASTLING_PATTERN.match(move_str)
        )

    def parse_and_validate_move(self, move_str: str) -> LegalityReport:
        """
        Parse a move in algebraic notation and validate it on the current board.
        
        Args:
            move_str: Move in algebraic notation (e.g., "e4", "Nf3", "O-O", "exd5")
        
        Returns:
            LegalityReport with validation result
        """
        move_str = move_str.strip().rstrip("+#?!")
        
        # Check notation
        if not self.validate_move_notation(move_str):
            return LegalityReport(
                is_legal=False,
                error_message=f"Invalid notation: '{move_str}'"
            )
        
        try:
            # Use python-chess to parse the move
            move = self.board.parse_san(move_str)
            
            # Double-check legality
            if move not in self.board.legal_moves:
                return LegalityReport(
                    is_legal=False,
                    error_message=f"Illegal move: '{move_str}' in position {self.board.fen()}"
                )
            
            return LegalityReport(
                is_legal=True,
                move_object=move,
                position_fen=self.board.fen()
            )
        
        except Exception as e:
            return LegalityReport(
                is_legal=False,
                error_message=f"Parse error for '{move_str}': {str(e)}"
            )

    def apply_move(self, move: chess.Move) -> None:
        """Apply a validated move to the board."""
        self.board.push(move)

    def validate_game_pgn(self, pgn_text: str) -> Tuple[bool, List[str]]:
        """
        Validate an entire game from PGN format.
        
        Args:
            pgn_text: Full PGN game text
        
        Returns:
            (is_valid, list_of_error_messages)
        """
        errors = []
        self.reset_board()

        # First, manually extract and validate moves from the movetext
        # This catches illegal moves that python-chess PGN parser might skip
        pgn_content = pgn_text.split("\n\n", 1)
        movetext = pgn_content[1].strip() if len(pgn_content) > 1 else pgn_text.strip()
        
        # Remove headers if still present
        lines = movetext.split("\n")
        movetext_lines = [line for line in lines if not line.strip().startswith("[")]
        movetext = " ".join(movetext_lines).strip()
        
        if movetext:
            # Extract all move tokens from movetext
            extracted_moves = self._extract_moves_from_pgn(movetext)
            
            # Debug: print extracted moves
            import logging
            logger = logging.getLogger(__name__)
            logger.debug(f"Extracted moves: {extracted_moves}")
            
            # Validate each move manually
            temp_board = chess.Board()
            for i, move_str in enumerate(extracted_moves):
                try:
                    move = temp_board.parse_san(move_str)
                    if move not in temp_board.legal_moves:
                        errors.append(f"Move {i+1}: '{move_str}' is illegal")
                        return False, errors
                    temp_board.push(move)
                except chess.InvalidMoveError as e:
                    errors.append(f"Move {i+1}: '{move_str}' is an invalid move: {e}")
                    return False, errors
                except chess.IllegalMoveError as e:
                    errors.append(f"Move {i+1}: '{move_str}' is an illegal move: {e}")
                    return False, errors
                except chess.AmbiguousMoveError as e:
                    errors.append(f"Move {i+1}: '{move_str}' is ambiguous: {e}")
                    return False, errors
                except ValueError as e:
                    errors.append(f"Move {i+1}: '{move_str}' parse error: {e}")
                    return False, errors
                except Exception as e:
                    errors.append(f"Move {i+1}: '{move_str}' unexpected error: {e}")
                    return False, errors

        return True, errors

    def _extract_moves_from_pgn(self, movetext: str) -> List[str]:
        """
        Extract moves from PGN movetext (NOT full PGN, just the moves section).
        Handles move numbers, variations, comments (basic parsing).
        
        Args:
            movetext: The moves section of a PGN (e.g., "1. e4 e5 2. Nf3 Nc6")
        
        Returns:
            List of moves in algebraic notation
        """
        # Remove comments in curly braces
        moves_text = re.sub(r"\{[^}]*\}", "", movetext)
        
        # Remove variations in parentheses
        moves_text = re.sub(r"\([^)]*\)", "", moves_text)
        
        # Remove game result markers
        moves_text = re.sub(r"1-0|0-1|1/2-1/2|\*", "", moves_text)
        
        # Remove move numbers (e.g., "1.", "2.", "12...", etc.)
        moves_text = re.sub(r"\d+\.+", "", moves_text)
        
        # Extract moves (pattern matches SAN notation)
        # Matches: e4, Nf3, Bxe5, O-O, O-O-O, exd5, Qh4+, Nxf7#, e8=Q, etc.
        move_pattern = r"[KQRBN]?[a-h]?[1-8]?x?[a-h][1-8](?:=[QRBN])?[+#]?|O-O(?:-O)?"
        moves = re.findall(move_pattern, moves_text)
        
        # Filter empty strings
        moves = [m for m in moves if m]
        
        return moves

    def get_legal_moves(self) -> List[str]:
        """Get all legal moves in the current position in algebraic notation."""
        return [self.board.san(move) for move in self.board.legal_moves]

    def is_check(self) -> bool:
        """Is the current side to move in check?"""
        return self.board.is_check()

    def is_checkmate(self) -> bool:
        """Is the current position checkmate?"""
        return self.board.is_checkmate()

    def is_stalemate(self) -> bool:
        """Is the current position stalemate?"""
        return self.board.is_stalemate()

    def get_board_state(self) -> str:
        """Get current board state as FEN."""
        return self.board.fen()

    def get_game_status(self) -> str:
        """Get the outcome of the game (ongoing, checkmate, stalemate, insufficient material, etc)."""
        if self.board.is_checkmate():
            return "CHECKMATE"
        elif self.board.is_stalemate():
            return "STALEMATE"
        elif self.board.is_insufficient_material():
            return "INSUFFICIENT_MATERIAL"
        elif self.board.is_seventyfive_moves():
            return "75_MOVE_RULE"
        elif self.board.is_fivefold_repetition():
            return "FIVEFOLD_REPETITION"
        elif self.board.can_claim_draw():
            return "DRAW_AVAILABLE"
        else:
            return "ONGOING"


# Example usage and testing
if __name__ == "__main__":
    validator = LegalityValidator()
    
    # Test 1: Single move validation
    print("=" * 60)
    print("TEST 1: Single Move Validation")
    print("=" * 60)
    
    test_moves = ["e4", "e5", "Nf3", "Nc6", "Bb5"]
    for move_str in test_moves:
        report = validator.parse_and_validate_move(move_str)
        print(f"{move_str}: {'✓ LEGAL' if report.is_legal else '✗ ILLEGAL'}")
        if not report.is_legal:
            print(f"  Error: {report.error_message}")
        validator.apply_move(report.move_object)
    
    # Test 2: Illegal move detection
    print("\n" + "=" * 60)
    print("TEST 2: Illegal Move Detection")
    print("=" * 60)
    
    validator.reset_board()
    illegal_moves = ["e5", "Nf6"]  # These are illegal on move 1 for white
    for move_str in illegal_moves:
        report = validator.parse_and_validate_move(move_str)
        print(f"{move_str}: {'✓ LEGAL' if report.is_legal else '✗ ILLEGAL'}")
        if not report.is_legal:
            print(f"  Error: {report.error_message}")
    
    # Test 3: Full game validation
    print("\n" + "=" * 60)
    print("TEST 3: Full Game Validation (Scholar's Mate)")
    print("=" * 60)
    
    scholar_mate_pgn = """
    [Event "Scholar's Mate Example"]
    [Site "Test"]
    [Date "2024.01.31"]
    [White "Test"]
    [Black "Test"]
    
    1. e4 e5 2. Bc4 Nc6 3. Qh5 Nf6?? 4. Qxf7#
    """
    
    is_valid, errors = validator.validate_game_pgn(scholar_mate_pgn)
    print(f"Game valid: {is_valid}")
    if errors:
        for error in errors:
            print(f"  Error: {error}")
    else:
        print(f"  Final position: {validator.get_game_status()}")
        print(f"  FEN: {validator.get_board_state()}")
